// Import the componentToWadm function from the wasmcloud:tools/convert interface,
// we will compose with the Rust component to satisfy the import.
//@ts-expect-error -- these types aren't currently generated by JCO
import { componentToWadm as componentConvert } from "wasmcloud:tools/convert";

// Implement the wasmcloud:tools/convert.componentToWadm function to convert a component to a WADM manifest
function componentToWadm(
  component: Uint8Array,
  name: string,
  description: string,
  version: string,
  image: string
): string {
  return componentConvert(component, name, description, version, image);
}

// Export the function for wasmcloud:tools/convert as specified in our WIT world
export const convert = {
  componentToWadm,
};
